export const PageConfig = {
  url: '/certification/list',
  detailUrl: '/certification/list/:id',
  moduleTitle: 'Sertifikasi Siswa',
  pageTitle: 'Daftar Sertifikasi',
  baseEnpoint: '/cms/master/certifications',
  primaryKey: 'id',
  maxBottomIndexDropdown: 2,
  enableSearchTools: true,
  enableTools: true,
  enableExportTools: true,
  enableTemplateTools: false,
  enableImportTools: false,
  enableFilterTools: true,
  enableActions: true,
  enableCreate: true,
  enableDetails: false,
  enableEdit: true,
  enableDelete: true,
  enableBulkDelete: false,
  enablePagination: true,
  enableLimitPerPage: true,
  enableRefreshTable: false,
  listFields: [
    {
      key: 'name',
      label: 'Nama Sertifikasi',
      sortable: true,
      width: 200,
      is_show: true,
    },
    {
      key: 'description',
      label: 'Deskripsi',
      sortable: true,
      width: 'auto',
      is_show: true,
    },
    {
      key: 'status',
      label: 'Status',
      sortable: true,
      width: 120,
      is_show: true,
      status: true,
      target: 'status_label',
    },
  ],
};
