export const PageConfig = {
  url: '/assesment/verbal',
  detailUrl: '/student/payment/:id',
  moduleTitle: 'Modul Pelatihan',
  moduleSlug: 'payment',
  pageTitle: 'Daftar Siswa',
  baseEnpoint: '/training/assesment-verbal',
  primaryKey: 'id',
  maxBottomIndexDropdown: 2,
  enableSearchTools: true,
  enableTools: false,
  enableExportTools: true,
  enableExportSingleTools: true,
  enableTemplateTools: true,
  enableImportTools: false,
  enableFilterTools: true,
  enableActions: true,
  enableCreate: true,
  enableDetails: false,
  enableEdit: true,
  enableDelete: false,
  enableBulkDelete: false,
  enablePagination: true,
  enableLimitPerPage: true,
  enableRefreshTable: false,
  listFields: [
    {
      key: 'id',
      label: 'ID',
      sortable: false,
      width: 'auto',
      is_show: false,
    },
    {
      key: 'user.name',
      label: 'Nama Siswa',
      sortable: true,
      width: 'auto',
      is_show: true,
    },
    {
      key: 'working_date',
      label: 'Tanggal & Waktu',
      sortable: true,
      width: 'auto',
      is_show: true,
    },
    {
      key: 'is_scheduled',
      label: 'Status',
      sortable: true,
      width: 'auto',
      is_show: true,
      status_schedule: true,
      target: 'is_scheduled',
    },
  ],
};
