export const PageConfig = {
  url: '/certification/result',
  detailUrl: '/certification/result/:id',
  moduleTitle: 'Sertifikasi Siswa',
  pageTitle: 'Hasil Sertifikasi',
  baseEnpoint: '/cms/master/certification-students',
  primaryKey: 'id',
  maxBottomIndexDropdown: 2,
  enableSearchTools: true,
  enableTools: true,
  enableExportTools: true,
  enableTemplateTools: false,
  enableImportTools: false,
  enableFilterTools: true,
  enableActions: true,
  enableCreate: false,
  enableDetails: true,
  enableEdit: true,
  enableDelete: false,
  enableBulkDelete: false,
  enablePagination: true,
  enableLimitPerPage: true,
  enableRefreshTable: false,
  listFields: [
    {
      key: 'user.name',
      label: 'Nama Siswa',
      sortable: true,
      width: 200,
      is_show: true,
    },
    {
      key: 'updated_at',
      label: 'Pembaruan Terakhir',
      sortable: true,
      width: 300,
      is_show: true,
    },
    {
      key: 'status',
      label: 'Status Kelulusan',
      sortable: false,
      width: 120,
      is_show: true,
      status: true,
      target: 'status_label',
    },
  ],
  listFieldsDetail: [
    {
      key: 'cert_date',
      label: 'Tanggal',
      sortable: true,
      width: 200,
      is_show: true,
    },
    {
      key: 'certification.name',
      label: 'Tipe Sertifikasi',
      sortable: true,
      width: 'auto',
      is_show: true,
    },
    {
      key: 'certification.link',
      label: 'Lokasi Sertifikasi',
      sortable: true,
      width: 'auto',
      is_show: true,
    },
    {
      key: 'file.filename',
      label: 'Lampiran',
      sortable: false,
      width: 200,
      is_show: true,
      file: true,
    },
    {
      key: 'status',
      label: 'Status',
      sortable: false,
      width: 160,
      is_show: true,
      status: true,
      target: 'status_label',
    },
  ],
};
