export const PageConfig = {
  url: '/wawancara',
  detailUrl: '/wawancara/:id',
  moduleTitle: 'Wawancara',
  pageTitle: 'Daftar Siswa',
  baseEnpoint: '/training/interviews',
  primaryKey: 'id',
  maxBottomIndexDropdown: 2,
  enableSearchTools: true,
  enableTools: true,
  enableExportTools: true,
  enableTemplateTools: false,
  enableImportTools: false,
  enableFilterTools: true,
  enableActions: true,
  enableCreate: false,
  enableCreateDetail: true,
  enableDetails: false,
  enableEdit: true,
  enableDelete: false,
  enableDeleteDetail: true,
  enableBulkDelete: false,
  enablePagination: true,
  enableLimitPerPage: true,
  enableRefreshTable: false,
  listFields: [
    {
      key: 'name',
      label: 'Nama Siswa',
      sortable: true,
      width: 200,
      is_show: true,
    },
    {
      key: 'training_program',
      target: 'training_program_label',
      label: 'Program Pelatihan',
      sortable: true,
      width: 'auto',
      is_show: true,
    },
    {
      key: 'interview_count',
      label: 'Total Wawancara',
      sortable: true,
      is_num: true,
      width: 'auto',
      is_show: true,
    },
    {
      key: 'interview_status',
      label: 'Status Kelulusan',
      sortable: false,
      width: 120,
      is_show: true,
      status: true,
      target: 'interview_status_label',
    },
  ],
  listFieldsDetail: [
    {
      key: 'interview_date',
      label: 'Tanggal & Waktu',
      sortable: true,
      width: 200,
      is_show: true,
    },
    {
      key: 'type_label',
      label: 'Tujuan',
      sortable: true,
      width: 'auto',
      is_show: true,
    },
    {
      key: 'name',
      label: 'Pewawancara',
      sortable: true,
      width: 'auto',
      is_show: true,
    },
    {
      key: 'agency',
      label: 'Instansi',
      sortable: true,
      width: 'auto',
      is_show: true,
      file: true,
    },
  ],
};
