const icons = {
  home: require("../assets/icons/home.png"),
  arrowLeft: require("../assets/icons/arrow-left.png"),
  arrowRight2: require("../assets/icons/arrow-right2.png"),
  avatar: require("../assets/icons/avatar.png"),
  bell: require("../assets/icons/bell.png"),
  logoHeader: require("../assets/icons/logo-header.png"),
  checklistBox: require("../assets/icons/checklist-box.png"),
  japanBook: require("../assets/icons/japan-book.png"),
  checkbox: require("../assets/icons/checkbox.png"),
  arrowRight: require("../assets/icons/arrow-right.png"),
  thumb: require("../assets/icons/thumb.png"),
  comment: require("../assets/icons/comment.png"),
  box: require("../assets/icons/box.png"),
  sheet: require("../assets/icons/sheet.png"),
  warningRed: require("../assets/icons/warning-red.png"),
  trash: require("../assets/icons/trash-icon.png"),
  playButton: require("../assets/icons/play-button.png"),

  leftArrow: require("../assets/icons/left-arrow.png"),
  rightArrow: require("../assets/icons/right-arrow.png"),

  selectedProperties: require("../assets/icons/bottom-tab/selected-properties.png"),
  bottomDefault: {
    chat: require("../assets/icons/bottom-tab/chat.png"),
    home: require("../assets/icons/bottom-tab/home.png"),
    pencil: require("../assets/icons/bottom-tab/pencil.png"),
    profile: require("../assets/icons/bottom-tab/profile.png"),
    document: require("../assets/icons/bottom-tab/document.png"),
    progress: require("../assets/icons/bottom-tab/progress.png"),
  },

  bottomSelected: {
    chat: require("../assets/icons/bottom-tab/selected-chat.png"),
    home: require("../assets/icons/bottom-tab/selected-home.png"),
    pencil: require("../assets/icons/bottom-tab/selected-pencil.png"),
    profile: require("../assets/icons/bottom-tab/selected-profile.png"),
    document: require("../assets/icons/bottom-tab/selected-document.png"),
    progress: require("../assets/icons/bottom-tab/selected-progress.png"),
  },
  eye: require("../assets/icons/show.png"),
  eyeSlash: require("../assets/icons/hide.png"),
  clearIcon: require("../assets/icons/clear.png"),
  google: require("../assets/icons/google.png"),
  facebook: require("../assets/icons/facebook.png"),
  apple: require("../assets/icons/apple.png"),
  calendar: require("../assets/icons/calendar.png"),
  upload: require("../assets/icons/upload.png"),
  iconX: require("../assets/icons/icon-x.png"),
  payment: require("../assets/icons/payment.png"),
  paymentJapan: require("../assets/icons/payment-japan.png"),
  pelatihan: require("../assets/icons/pelatihan.png"),
  pelatihanJapan: require("../assets/icons/pelatihan-japan.png"),
  sertifikasi: require("../assets/icons/sertifikasi.png"),
  sertifikasiJapan: require("../assets/icons/sertifikasi-japan.png"),
  wawancara: require("../assets/icons/wawancara.png"),
  wawancaraJapan: require("../assets/icons/wawancara-japan.png"),
  searchClose: require("../assets/icons/search-close.png"),
  iosRight: require("../assets/icons/ios-right.png"),
  search: require("../assets/icons/search.png"),
  clock: require("../assets/icons/clock.png"),
  markLesson: require("../assets/icons/markLesson.png"),
  iconFilterCalendar: require("../assets/icons/icon-filter-calendar.png"),
  pencilIcon: require("../assets/icons/pencil-icon.png"),
  calendarEvent: require("../assets/icons/calendar-event.png"),
  clockEvent: require("../assets/icons/clock-event.png"),
  link: require("../assets/icons/link.png"),
  download: require("../assets/icons/download.png"),
  plus: require("../assets/icons/plus.png"),
  hamburger: require("../assets/icons/hamburger.png"),

  forum: {
    curhat: require("../assets/icons/topik-forum/curhat.png"),
    diskusiUmum: require("../assets/icons/topik-forum/diskusi-umum.png"),
    pap: require("../assets/icons/topik-forum/pap.png"),
    praktikalJepang: require("../assets/icons/topik-forum/praktikal-jepang.png"),
    softSkill: require("../assets/icons/topik-forum/soft-skill.png"),
    teoriJepang: require("../assets/icons/topik-forum/teori-jepang.png"),

    curhatSelected: require("../assets/icons/topik-forum/curhat-selected.png"),
    diskusiUmumSelected: require("../assets/icons/topik-forum/diskusi-umum-selected.png"),
    papSelected: require("../assets/icons/topik-forum/pap-selected.png"),
    praktikalJepangSelected: require("../assets/icons/topik-forum/praktikal-jepang-selected.png"),
    softSkillSelected: require("../assets/icons/topik-forum/soft-skill-selected.png"),
    teoriJepangSelected: require("../assets/icons/topik-forum/teori-jepang-selected.png"),
  },
  pencilRed: require("../assets/icons/pencil-red.png"),
  close: require("../assets/icons/close.png"),
  share: require("../assets/icons/share.png"),
  forumLike: require("../assets/icons/forum-like.png"),
  like: require("../assets/icons/like.png"),
  report: require("../assets/icons/report.png"),
  likeBorder: require("../assets/icons/like-border.png"),
  sort: require("../assets/icons/sort.png"),
  filter: require("../assets/icons/filter.png"),
  calendarEventGray: require("../assets/icons/calendar-event-gray.png"),
  trashRed: require("../assets/icons/trash-red.png"),
  checklist: require("../assets/icons/checklist.png"),
  checklistGreen: require("../assets/icons/checklist-green.png"),
  dividerLine: require("../assets/icons/divider-line.png"),
  flag: require("../assets/icons/flag.png"),
  flower: require("../assets/icons/flower.png"),
  wallet: require("../assets/icons/wallet.png"),
  message: require("../assets/icons/message.png"),
  whatsappIcon: require("../assets/icons/whatsapp-icon.png"),
  burger: require("../assets/icons/burger.png"),
  arrowUp: require("../assets/icons/arrow-up.png"),
  arrowBottom: require("../assets/icons/arrow-bottom.png"),
  searchSuccess: require("../assets/icons/search-success.png"),
  calendarRed: require("../assets/icons/calendar-red.png"),
  calendarTest: require("../assets/icons/calendar-test.png"),
  clockTest: require("../assets/icons/clock-test.png"),
  linkTest: require("../assets/icons/link-test.png"),
  document: require("../assets/icons/document.png"),
  documentStone400: require("../assets/icons/documentStone400.png"),
  playAudio: require("../assets/icons/play-audio.png"),
  divider: require("../assets/icons/divider.png"),
  book: require("../assets/icons/book1.png"),
  checkboxBlack: require("../assets/icons/checkbox-black.png"),
  lock: require("../assets/icons/lock.png"),
  successGreen: require("../assets/icons/success-green.png"),
  fileIcon: require("../assets/icons/file-icon.png"),
  toggle: require("../assets/icons/toggle.png"),
  toggleSelected: require("../assets/icons/toggle-selected.png"),

  materiDokumen: require("../assets/materi/dokumen.png"),
  materi: require("../assets/materi/materi.png"),
  materiRepeat: require("../assets/materi/repeat.png"),
  materiSuccess: require("../assets/materi/materi_success.png"),
  materiVideo: require("../assets/materi/materiVideo.png"),
  materiDokumenOutline: require("../assets/materi/dokumen_outline.png"),
  correctedRed: require("../assets/icons/corrected-red.png"),
  camera: require("../assets/icons/camera.png"),
  speaker: require("../assets/icons/speaker.png"),

  btnDelete: require("../assets/icons/btn-delete.png"),
  btnStop: require("../assets/icons/btn-stop.png"),
  btnPlay: require("../assets/icons/btn-play.png"),
};

export default icons;
