export const PageConfig = {
  url: '/cms/finance/batch-users',
  detailUrl: '/cms/finance/batch-users/:id',
  moduleTitle: 'Siswa Wiwitan',
  moduleSlug: 'batch-users',
  pageTitle: 'Harga Paket',
  baseEnpoint: '/cms/finance/batch-users',
  primaryKey: 'id',
  maxBottomIndexDropdown: 2,
  enableSearchTools: true,
  enableTools: false,
  enableExportTools: true,
  enableExportSingleTools: true,
  enableTemplateTools: true,
  enableImportTools: false,
  enableFilterTools: true,
  enableActions: true,
  enableCreate: false,
  enableDetails: true,
  enableEdit: false,
  enableDelete: false,
  enableBulkDelete: false,
  enablePagination: false,
  enableLimitPerPage: true,
  enableRefreshTable: false,
  listFields: [
    {
      key: 'id',
      label: 'ID',
      sortable: false,
      width: 'auto',
      is_show: false,
    },
    {
      key: 'index_label_installment',
      label: 'Cicilan',
      sortable: false,
      width: 'auto',
      is_show: true,
    },
    {
      key: 'index',
      label: 'Cicilan',
      sortable: false,
      width: 'auto',
      is_show: false,
    },
    {
      key: 'paymentProof.amount',
      label: 'Nominal',
      type: 'currency',
      sortable: false,
      width: 'auto',
      is_show: true,
    },
    {
      key: 'paymentProof.created_at',
      label: 'Tanggal Pembayaran',
      type: 'date',
      sortable: false,
      width: 'auto',
      is_show: true,
    },
    {
      key: 'paymentProof.file.url',
      label: 'Bukti Pembayaran',
      sortable: false,
      width: 'auto',
      linkPayment: true,
      is_show: true,
    },
  ],
};
