require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '13.4'
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'Wiwitan' do
  use_expo_modules!
  post_integrate do |installer|
    begin
      expo_patch_react_imports!(installer)
    rescue => e
      Pod::UI.warn e
    end
  end
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()
  
  pod 'Firebase', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true
  $RNFirebaseAsStaticFramework = true

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    # Upcoming versions of React Native may rely on get_default_flags(), but
    # we make it explicit here to aid in the React Native upgrade process.
    :hermes_enabled => true,
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      # Set `mac_catalyst_enabled` to `true` in order to apply patches
      # necessary for Mac Catalyst builds
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
    installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      
      # Exclude simulator architectures ONLY for problematic Objective-C pods
      case target.name
      when "TOCropViewController","RNImageCropPicker"
        config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64 x86_64"
      else
        config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] ||= ""
      end

      # Ensure all Swift pods (like ExpoModulesProvider) compile arm64
      if target.name.include?("Expo") || target.name.include?("RN")
        config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] ||= ""
      end

      # Optional: fixes some Xcode warnings
      config.build_settings["ONLY_ACTIVE_ARCH"] = "NO"
    end
  end
    #__apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end


target 'NotificationServices' do
  pod 'Firebase/Messaging', '~> 10.20.0' # eg 6.31.0
  
  pod 'Firebase', :modular_headers => true
  pod 'FirebaseCoreInternal', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true
end
