export const PageConfig = {
  url: '',
  detailUrl: '',
  moduleTitle: 'Kelas Virtual',
  pageTitle: 'Tabel Kelas Virtual',
  baseEnpoint: '/training/course-items/virtual-class',
  primaryKey: 'id',
  maxBottomIndexDropdown: 2,
  enableSearchTools: true,
  enableTools: true,
  enableExportTools: false,
  enableTemplateTools: false,
  enableImportTools: false,
  enableFilterTools: true,
  enableActions: false,
  enableCreate: false,
  enableDetail: false,
  enableEdit: true,
  enableDelete: true,
  enableBulkDelete: false,
  enablePagination: false,
  enableLimitPerPage: true,
  enableRefreshTable: false,
  listFields: [
    {
      key: 'question.title',
      label: 'Soal',
      sortable: false,
      width: 453,
      is_show: true,
    },
    {
      key: 'question.type_label',
      label: 'Tipe Soal',
      sortable: false,
      width: 453,
      is_show: true,
    },
    {
      key: 'answare',
      label: 'Jawaban Siswa',
      sortable: false,
      width: 453,
      is_show: true,
      type: 'answer',
    },
    {
      key: 'a_weight',
      label: 'Poin',
      sortable: false,
      width: 453,
      is_show: true,
      type: 'poin',
    },
  ],
};
