export const PageConfig = {
  url: '/management/user',
  createUrl: '/management/user/create',
  editUrl: '/management/user/edit/:id',
  detailUrl: '/management/user/detail/:id',
  moduleTitle: 'Daftar Pengguna',
  pageTitle: 'List Daftar Pengguna',
  createTitle: 'Buat Pengguna Baru',
  editTitle: 'Edit Pengguna',
  baseEnpoint: '/base/users',
  primaryKey: 'id',
  maxBottomIndexDropdown: 2,
  enableSearchTools: true,
  enableTools: true,
  enableExportTools: false,
  enableTemplateTools: false,
  enableImportTools: false,
  enableFilterTools: false,
  enableActions: true,
  enableCreate: true,
  enableDetail: false,
  enableEdit: true,
  enableDelete: true,
  enableBulkDelete: false,
  enablePagination: true,
  enableLimitPerPage: true,
  enableRefreshTable: false,
  listFields: [
    {
      key: 'name',
      label: 'Nama',
      sortable: true,
      width: 200.4,
      is_show: true,
    },
    {
      key: 'role.name',
      label: 'Role',
      type: 'role',
      sortable: true,
      width: 200.4,
      is_show: true,
    },
    {
      key: 'email',
      label: 'Email',
      sortable: false,
      width: 200.4,
      is_show: true,
    },
    {
      key: 'is_active',
      label: 'Status',
      sortable: false,
      width: 200.4,
      is_show: true,
      status: true,
      target: 'is_active_label',
    },
  ],
};
