export const PageConfig = {
  url: '/training/score',
  detailUrl: '/training/score/:id',
  moduleTitle: 'Buku Nilai Siswa',
  pageTitle: 'Tabel Buku Nilai Siswa',
  baseEnpoint: '/training/student-report',
  primaryKey: 'id',
  maxBottomIndexDropdown: 2,
  enableSearchTools: true,
  enableTools: true,
  enableExportTools: true,
  enableTemplateTools: false,
  enableImportTools: false,
  enableFilterTools: true,
  enableActions: true,
  enableCreate: false,
  enableDetail: true,
  enableEdit: false,
  enableDelete: false,
  enableBulkDelete: false,
  enablePagination: true,
  enableLimitPerPage: true,
  enableRefreshTable: false,
  listFields: [
    {
      key: 'user_name',
      label: 'Nama Siswa',
      sortable: true,
      width: 155.5,
      is_show: true,
    },
    {
      key: 'program_type_label',
      label: 'Program Pelatihan',
      sortable: false,
      width: 155.5,
      is_show: true,
    },
    {
      key: 'module_name',
      label: 'Nama Modul',
      sortable: false,
      width: 155.5,
      is_show: true,
    },
    {
      key: 'type_assesment',
      label: 'Tipe Asesmen',
      sortable: true,
      width: 155.5,
      is_show: true,
    },
    {
      key: 'category_module',
      label: 'Kategori Modul',
      sortable: true,
      width: 155.5,
      is_show: true,
    },
    {
      key: 'weight_final',
      label: 'Nilai',
      sortable: true,
      width: 155.5,
      is_show: true,
    },
  ],
};
