export const PageConfig = {
  url: '/dashboard/log-aktifitas',
  detailUrl: '/dashboard/log-aktifitas/:id',
  moduleTitle: 'Dashboard',
  pageTitle: 'Log Aktifitas',
  baseEnpoint: '/base/activity-log',
  primaryKey: 'id',
  maxBottomIndexDropdown: 2,
  enableSearchTools: true,
  enableTools: true,
  enableExportTools: false,
  enableTemplateTools: false,
  enableImportTools: false,
  enableFilterTools: true,
  enableActions: true,
  enableCreate: true,
  enableDetail: true,
  enableEdit: true,
  enableDelete: true,
  enableBulkDelete: false,
  enablePagination: true,
  enableLimitPerPage: true,
  enableRefreshTable: false,
  listFields: [],
};
