export const PageConfig = {
  url: '/notification',
  createUrl: '/notification/create',
  editUrl: '/notification/edit/:id',
  detailUrl: '/notification/detail/:id',
  moduleTitle: 'Konten Notifikasi',
  pageTitle: 'List Konten Notifikasi',
  createTitle: 'Buat Konten Notifikasi',
  editTitle: 'Edit Konten Notifikasi',
  baseEnpoint: '/master/content-notifications',
  primaryKey: 'id',
  maxBottomIndexDropdown: 2,
  enableSearchTools: true,
  enableTools: true,
  enableExportTools: false,
  enableTemplateTools: false,
  enableImportTools: false,
  enableFilterTools: true,
  enableActions: true,
  enableCreate: true,
  enableDetail: false,
  enableEdit: true,
  enableDelete: true,
  enableBulkDelete: false,
  enablePagination: true,
  enableLimitPerPage: true,
  enableRefreshTable: false,
  listFields: [
    {
      key: 'name',
      label: 'Judul Notifikasi',
      sortable: true,
      width: 200,
      is_show: true,
    },
    {
      key: 'repeat_each',
      target: 'repeat_each_label',
      label: 'Pengulangan',
      sortable: true,
      width: 200,
      is_show: true,
    },
    {
      key: 'send_at',
      label: 'Tanggal Notifikasi',
      type: 'date',
      sortable: true,
      width: 200,
      is_show: true,
    },
    {
      key: 'status',
      label: 'Status',
      sortable: false,
      width: 200,
      is_show: true,
      status: true,
      target: 'status_label',
    },
  ],
};
