export const PageConfig = {
  url: '/training/category',
  detailUrl: '/training/category/:id',
  moduleTitle: 'Kategori Modul',
  pageTitle: 'Tabel Kategori Modul',
  baseEnpoint: '/training/courses',
  primaryKey: 'id',
  maxBottomIndexDropdown: 2,
  enableSearchTools: true,
  enableTools: true,
  enableExportTools: true,
  enableTemplateTools: false,
  enableImportTools: false,
  enableFilterTools: true,
  enableActions: true,
  enableCreate: true,
  enableDetails: false,
  enableEdit: true,
  enableDelete: true,
  enableBulkDelete: false,
  enablePagination: true,
  enableLimitPerPage: true,
  enableRefreshTable: false,
  listFields: [
    {
      key: 'title',
      label: 'Kategori Modul',
      sortable: false,
      width: 'auto',
      is_show: true,
    },

    {
      key: 'type',
      label: 'Tipe Pembelajaran',
      sortable: true,
      width: 'auto',
      is_show: true,
      status: true,
      target: 'type_label',
    },
  ],
};
