export const PageConfig = {
  url: '/seminar',
  createUrl: '/seminar/create',
  editUrl: '/seminar/edit/:id',
  detailUrl: '/seminar/detail/:id',
  moduleTitle: 'Seminar Wiwitan',
  pageTitle: 'List Seminar Wiwitan',
  createTitle: 'Buat Acara',
  editTitle: 'Edit Acara',
  baseEnpoint: '/cms/master/seminar',
  primaryKey: 'id',
  maxBottomIndexDropdown: 2,
  enableSearchTools: true,
  enableTools: true,
  enableExportTools: false,
  enableTemplateTools: false,
  enableImportTools: false,
  enableFilterTools: true,
  enableActions: true,
  enableCreate: true,
  enableDetail: true,
  enableEdit: true,
  enableDelete: true,
  enableBulkDelete: false,
  enablePagination: true,
  enableLimitPerPage: true,
  enableRefreshTable: false,
  listFields: [
    {
      key: 'name',
      label: 'Nama Acara',
      sortable: true,
      width: 200,
      is_show: true,
    },
    {
      key: 'started_at',
      label: 'Tanggal Mulai',
      type: 'date',
      sortable: true,
      width: 200,
      is_show: true,
    },
    {
      key: 'finished_at',
      label: 'Tanggal Selesai',
      type: 'date',
      sortable: true,
      width: 200,
      is_show: true,
    },
    {
      key: 'status',
      label: 'Status',
      sortable: false,
      width: 200,
      is_show: true,
      status: true,
      target: 'status_label',
    },
  ],
};
