# Replace the hostname before enabling this site.
server {
    listen 80;
    listen [::]:80;
    server_name cms.staging.example.com;

    root /srv/wiwitan/cms/build;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~ /\. {
        deny all;
    }
}
