export const PageConfig = {
  url: '',
  detailUrl: '',
  createUrl: '',
  moduleTitle: 'Asesmen',
  pageTitle: 'Asesmen',
  baseEnpoint: '/training/course-items/module',
  primaryKey: 'id',
  maxBottomIndexDropdown: 2,
  enableSearchTools: false,
  enableTools: false,
  enableExportTools: false,
  enableTemplateTools: false,
  enableImportTools: false,
  enableFilterTools: false,
  enableActions: false,
  enableCreate: false,
  enableDetail: false,
  enableEdit: false,
  enableDelete: false,
  enableBulkDelete: false,
  enablePagination: false,
  enableLimitPerPage: false,
  enableRefreshTable: false,
  listFields: [],
};
