export const PageConfig = {
  url: '',
  detailUrl: '',
  moduleTitle: 'Kelas Virtual',
  pageTitle: 'Tabel Kelas Virtual',
  baseEnpoint: '/training/course-items/virtual-class',
  primaryKey: 'id',
  maxBottomIndexDropdown: 2,
  enableSearchTools: true,
  enableTools: true,
  enableExportTools: false,
  enableTemplateTools: false,
  enableImportTools: false,
  enableFilterTools: true,
  enableActions: true,
  enableCreate: true,
  enableDetail: false,
  enableEdit: true,
  enableDelete: true,
  enableBulkDelete: false,
  enablePagination: true,
  enableLimitPerPage: true,
  enableRefreshTable: false,
  listFields: [
    {
      key: 'title',
      label: 'Nama Kelas Virtual',
      sortable: false,
      width: 453,
      is_show: true,
    },
    {
      key: 'started_at',
      label: 'Tanggal & Waktu',
      type: 'datetime',
      sortable: true,
      width: 453,
      is_show: true,
    },
  ],
};
