export const PageConfig = {
  url: '/student/payment',
  detailUrl: '/student/payment/:id',
  moduleTitle: 'Siswa Wiwitan',
  moduleSlug: 'payment',
  pageTitle: 'Daftar Siswa',
  baseEnpoint: '/cms/finance/batch-users',
  primaryKey: 'id',
  maxBottomIndexDropdown: 2,
  enableSearchTools: true,
  enableTools: false,
  enableExportTools: true,
  enableExportSingleTools: true,
  enableTemplateTools: true,
  enableImportTools: false,
  enableFilterTools: true,
  enableActions: true,
  enableCreate: false,
  enableDetails: true,
  enableEdit: false,
  enableDelete: false,
  enableBulkDelete: false,
  enablePagination: true,
  enableLimitPerPage: true,
  enableRefreshTable: false,
  listFields: [
    {
      key: 'id',
      label: 'ID',
      sortable: false,
      width: 'auto',
      is_show: false,
    },
    {
      key: 'user.name',
      label: 'Nama Siswa',
      sortable: true,
      width: 'auto',
      is_show: true,
    },
    {
      key: 'user.email',
      label: 'Email',
      sortable: true,
      width: 'auto',
      is_show: true,
    },
    {
      key: 'program.title',
      label: 'Program Pelatihan',
      sortable: true,
      width: 'auto',
      is_show: true,
    },
    {
      key: 'user.training_preference',
      label: 'Preferensi Pelatihan',
      sortable: true,
      width: 'auto',
      is_show: true,
      type: 'label',
      target: 'user.training_preference_label',
    },
    {
      key: 'transaction_status_administration',
      label: 'Administrasi',
      sortable: false,
      width: 'auto',
      is_show: true,
      administration: true,
      target: 'transaction_status_administration',
    },
    {
      key: 'transaction_status_training',
      label: 'Pelatihan',
      sortable: false,
      width: 'auto',
      is_show: true,
      training: true,
      target: 'transaction_status_training',
    },
  ],
};
