export const PageConfig = {
  url: '/student/list',
  detailUrl: '/student/list/:id',
  moduleTitle: 'Daftar Siswa',
  pageTitle: 'List Daftar Siswa',
  baseEnpoint: '/base/users',
  primaryKey: 'id',
  maxBottomIndexDropdown: 2,
  enableSearchTools: true,
  enableTools: true,
  enableExportTools: true,
  enableTemplateTools: false,
  enableImportTools: false,
  enableFilterTools: true,
  enableActions: true,
  enableCreate: false,
  enableDetail: false,
  enableEdit: true,
  enableDelete: false,
  enableBulkDelete: false,
  enablePagination: true,
  enableLimitPerPage: true,
  enableRefreshTable: false,
  listFields: [
    {
      key: 'name',
      label: 'Nama Siswa',
      sortable: true,
      width: 228.67,
      is_show: true,
    },
    {
      key: 'email',
      label: 'Email',
      sortable: false,
      width: 228.67,
      is_show: true,
    },
    {
      key: 'city.name',
      label: 'Domisili',
      sortable: true,
      width: 228.67,
      is_show: true,
    },
    {
      key: 'created_at',
      label: 'Tanggal Daftar',
      type: 'date',
      sortable: true,
      width: 140,
      is_show: true,
    },
    {
      key: 'is_active',
      label: 'Status',
      sortable: false,
      width: 107,
      is_show: true,
      status: true,
      target: 'is_active_label',
    },
  ],
};
