export const PageConfig = {
  url: '/training/list',
  detailUrl: '/training/list/detail/:id',
  createUrl: '/training/list/create',
  moduleTitle: 'Materi Pelatihan',
  pageTitle: 'Daftar Materi',
  baseEnpoint: '/training/course-items/module',
  primaryKey: 'id',
  maxBottomIndexDropdown: 2,
  enableSearchTools: true,
  enableTools: true,
  enableExportTools: true,
  enableTemplateTools: false,
  enableImportTools: false,
  enableFilterTools: true,
  enableActions: true,
  enableCreate: true,
  enableDetail: false,
  enableEdit: true,
  enableDelete: true,
  enableBulkDelete: false,
  enablePagination: true,
  enableLimitPerPage: true,
  enableRefreshTable: false,
  listFields: [
    {
      key: 'title',
      label: 'Nama Materi',
      sortable: false,
      width: 250.5,
      is_show: true,
    },
    {
      key: 'course.title',
      label: 'Kategori Modul',
      sortable: false,
      width: 250.5,
      is_show: true,
    },
    {
      key: 'module.title',
      label: 'Modul Pelatihan',
      sortable: false,
      width: 250.5,
      is_show: true,
    },
  ],
};
