export const PageConfig = {
  url: '/student/progress',
  detailUrl: '/student/progress/:id',
  moduleTitle: 'Progres Siswa',
  pageTitle: 'Daftar Siswa',
  baseEnpoint: '/base/users/progress',
  primaryKey: 'id',
  maxBottomIndexDropdown: 2,
  enableSearchTools: true,
  enableTools: true,
  enableExportTools: true,
  enableTemplateTools: false,
  enableImportTools: false,
  enableFilterTools: true,
  enableActions: true,
  enableCreate: false,
  enableDetail: true,
  enableEdit: false,
  enableDelete: false,
  enableBulkDelete: false,
  enablePagination: true,
  enableLimitPerPage: true,
  enableRefreshTable: false,
  listFields: [
    {
      key: 'name',
      label: 'Nama Siswa',
      sortable: true,
      width: 250,
      is_show: true,
    },
    {
      key: 'last_phase',
      label: 'Fase',
      sortable: true,
      width: 250,
      is_show: true,
      type: 'label',
      target: 'last_phase_label',
    },
    {
      key: 'progress',
      label: 'Fase Progress',
      type: 'progress',
      sortable: false,
      width: 250,
      is_show: true,
    },
  ],
};
