export const PageConfig = {
  url: '/student/payment',
  detailUrl: '/student/payment/:id',
  moduleTitle: 'Siswa Wiwitan',
  moduleSlug: 'payment',
  pageTitle: 'Data Pembayaran',
  baseEnpoint: '/base/users',
  primaryKey: 'id',
  maxBottomIndexDropdown: 2,
  enableSearchTools: true,
  enableTools: true,
  enableExportTools: true,
  enableTemplateTools: true,
  enableImportTools: true,
  enableFilterTools: true,
  enableActions: true,
  enableCreate: true,
  enableDetails: true,
  enableEdit: false,
  enableDelete: false,
  enableBulkDelete: false,
  enablePagination: true,
  enableLimitPerPage: true,
  enableRefreshTable: false,
  listFields: [
    {
      key: 'id',
      label: 'USER ID',
      sortable: true,
      width: 'auto',
      is_show: false,
    },
    {
      key: 'name',
      label: 'NAME',
      sortable: true,
      width: 'auto',
      is_show: true,
    },
    {
      key: 'email',
      label: 'EMAIL',
      sortable: true,
      width: 'auto',
      is_show: true,
    },
    {
      key: 'role.name',
      label: 'ROLE',
      sortable: true,
      width: 'auto',
      is_show: true,
    },
    {
      key: 'created_at',
      label: 'DATE CREATED',
      sortable: true,
      width: 'auto',
      is_show: true,
    },
    {
      key: 'is_active',
      label: 'STATUS',
      sortable: true,
      width: 'auto',
      is_show: true,
      status: true,
      target: 'status_label',
    },
  ],
};
