import { NAV_ITEM_TYPE_ITEM, NAV_ITEM_TYPE_COLLAPSE } from 'constants/navigation.constant';
import { PageConfig as StudentProgressConfig } from 'views/student/progress/config';
import { PageConfig as StudentListConfig } from 'views/student/list/config';
import { PageConfig as PaymentConfig } from 'views/student/payment/config';
import { PageConfig as SeminarConfig } from 'views/seminar/config';
import { PageConfig as TrainingModuleConfig } from 'views/training/module/config';

const navigationConfig = [
  {
    key: 'dashboard',
    path: '/dashboard',
    title: 'Dashboard',
    translateKey: 'nav.dashboard',
    icon: 'dashboard',
    type: NAV_ITEM_TYPE_ITEM,
    authority: ['dashboard'],
    subMenu: [],
  },
  {
    key: 'siswaWiwitan',
    path: '',
    title: 'Siswa Wiwitan',
    translateKey: 'nav.siswaWiwitan',
    icon: 'people',
    type: NAV_ITEM_TYPE_COLLAPSE,
    authority: ['siswa_wiwitan'],
    subMenu: [
      {
        key: 'studentData.list',
        path: StudentListConfig.url,
        title: 'Daftar Siswa',
        translateKey: 'nav.studentData.student',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: 'studentData.progress',
        path: StudentProgressConfig.url,
        title: 'Progres Siswa',
        translateKey: 'nav.studentData.progress',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: 'studentData.finance',
        path: PaymentConfig.url,
        title: 'Data Pembayaran',
        translateKey: 'nav.studentData.payment',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
    ],
  },
  {
    key: 'konfigurasiPraTes',
    path: '',
    title: 'Konfigurasi Pra Tes',
    translateKey: 'nav.konfigurasiPraTes',
    icon: 'config',
    type: NAV_ITEM_TYPE_COLLAPSE,
    authority: ['konfigurasi_pra_tes'],
    subMenu: [
      {
        key: 'test.language',
        path: '/test/language',
        title: 'Tes Bakat Bahasa',
        translateKey: 'nav.test.language',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: 'test.character',
        path: '/test/character',
        title: 'Tes karakter',
        translateKey: 'nav.test.character',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: 'test.qna',
        path: '/test/qna',
        title: 'Sesi QnA',
        translateKey: 'nav.test.qna',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
    ],
  },
  {
    key: 'materiPelatihan',
    path: '',
    title: 'Materi Pelatihan',
    translateKey: 'nav.materiPelatihan',
    icon: 'book',
    type: NAV_ITEM_TYPE_COLLAPSE,
    authority: ['materi_pelatihan'],
    subMenu: [
      {
        key: 'training.category',
        path: '/training/category',
        title: 'Kategori Modul',
        translateKey: 'nav.training.category',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: 'training.module',
        path: TrainingModuleConfig.url,
        title: 'Modul Pelatihan',
        translateKey: 'nav.training.module',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: 'training.list',
        path: '/training/list',
        title: 'Daftar Materi',
        translateKey: 'nav.training.list',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: 'training.score',
        path: '/training/score',
        title: 'Buku Nilai Siswa',
        translateKey: 'nav.training.score',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
    ],
  },
  {
    key: 'page.studentCertification',
    path: '',
    title: 'Sertifikasi Siswa',
    translateKey: 'nav.page.studentCertification',
    icon: 'certificateKanji',
    type: NAV_ITEM_TYPE_COLLAPSE,
    authority: ['hasil_sertifikasi_siswa'],
    subMenu: [
      {
        key: 'cert.list',
        path: '/certification/list',
        title: 'Daftar Sertifikasi',
        translateKey: 'nav.cert.list',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: 'cert.result',
        path: '/certification/result',
        title: 'Hasil Sertifikasi',
        translateKey: 'nav.cert.result',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
    ],
  },
  {
    key: 'page.wawancara',
    path: '/wawancara',
    title: 'Wawancara Final',
    translateKey: 'nav.page.wawancara',
    icon: 'certificate',
    type: NAV_ITEM_TYPE_ITEM,
    authority: ['wawancara_final'],
    subMenu: [],
  },
  {
    key: 'page.forum',
    path: '/forum',
    title: 'Forum Diskusi',
    translateKey: 'nav.page.forum',
    icon: 'chat',
    type: NAV_ITEM_TYPE_ITEM,
    authority: ['forum_diskusi'],
    subMenu: [],
  },
  {
    key: 'page.notification',
    path: '/notification',
    title: 'Konten Notifikasi',
    translateKey: 'nav.page.notification',
    icon: 'bell',
    type: NAV_ITEM_TYPE_ITEM,
    authority: ['konten_notifikasi'],
    subMenu: [],
  },
  {
    key: 'page.seminar',
    path: SeminarConfig.url,
    title: 'Seminar Wiwitan',
    translateKey: 'nav.page.seminar',
    icon: 'seminar',
    type: NAV_ITEM_TYPE_ITEM,
    authority: ['seminar_wiwitan'],
    subMenu: [],
  },
  {
    key: 'admin',
    path: '',
    title: 'Manajemen Admin',
    translateKey: 'nav.admin',
    icon: 'accountSetting',
    type: NAV_ITEM_TYPE_COLLAPSE,
    authority: ['manajemen_admin'],
    subMenu: [
      {
        key: 'admin.role',
        path: '/management/role',
        title: 'Daftar Role',
        translateKey: 'nav.admin.role',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: 'admin.user',
        path: '/management/user',
        title: 'Daftar Pengguna',
        translateKey: 'nav.admin.user',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
    ],
  },
  {
    key: 'setting',
    path: '',
    title: 'Pengaturan',
    translateKey: 'nav.setting',
    icon: 'gear',
    type: NAV_ITEM_TYPE_COLLAPSE,
    authority: ['pengaturan'],
    subMenu: [
      {
        key: 'setting.profile',
        path: '/setting/profile',
        title: 'Profile',
        translateKey: 'nav.setting.profile',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: 'setting.sistem',
        path: '/setting/sistem',
        title: 'Sistem',
        translateKey: 'nav.setting.sistem',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
    ],
  },
  {
    key: 'logout',
    path: '',
    title: 'Keluar',
    translateKey: 'nav.logout',
    icon: 'logout',
    type: NAV_ITEM_TYPE_ITEM,
    authority: [],
    subMenu: [],
    logout: true,
  },
];

export default navigationConfig;
