export const PageConfig = {
  url: '/cms/finance/prices',
  detailUrl: '/cms/finance/prices/:id',
  moduleTitle: 'Siswa Wiwitan',
  moduleSlug: 'payment',
  pageTitle: 'Harga Paket',
  baseEnpoint: '/cms/finance/prices',
  primaryKey: 'id',
  maxBottomIndexDropdown: 2,
  enableSearchTools: true,
  enableTools: false,
  enableExportTools: true,
  enableExportSingleTools: true,
  enableTemplateTools: true,
  enableImportTools: false,
  enableFilterTools: true,
  enableActions: true,
  enableCreate: false,
  enableDetails: true,
  enableEdit: false,
  enableDelete: false,
  enableBulkDelete: false,
  enablePagination: true,
  enableLimitPerPage: true,
  enableRefreshTable: false,
  listFields: [
    {
      key: 'id',
      label: 'ID',
      sortable: false,
      width: 'auto',
      is_show: false,
    },
    {
      key: 'type_label',
      label: 'Tipe Pembayaran',
      sortable: true,
      width: 'auto',
      is_show: true,
    },
    {
      key: 'program.title',
      label: 'Program Pelatihan',
      sortable: true,
      width: 'auto',
      is_show: true,
    },
    {
      key: 'subtype',
      target: 'subtype_label',
      label: 'Preferensi',
      sortable: true,
      width: 'auto',
      is_show: true,
    },
    {
      key: 'amount',
      type: 'currency',
      label: 'Harga Paket',
      sortable: true,
      width: 'auto',
      is_show: true,
    },
  ],
};
