export const PageConfig = {
  url: '',
  detailUrl: '',
  moduleTitle: 'Dokumen Siswa',
  pageTitle: 'Dokumen Siswa',
  baseEnpoint: '/base/user-files',
  primaryKey: 'id',
  maxBottomIndexDropdown: 2,
  enableSearchTools: true,
  enableTools: true,
  enableExportTools: false,
  enableTemplateTools: false,
  enableImportTools: false,
  enableFilterTools: true,
  enableActions: true,
  enableCreate: false,
  enableDetail: false,
  enableEdit: false,
  enableDownload: true,
  enableDelete: true,
  enableBulkDelete: false,
  enablePagination: true,
  enableLimitPerPage: true,
  enableRefreshTable: false,
  listFields: [
    {
      key: 'slug',
      label: 'Dokumen',
      sortable: true,
      width: 226.5,
      is_show: true,
    },
    {
      key: 'type',
      label: 'Tipe Dokumen',
      sortable: true,
      width: 226.5,
      is_show: true,
      type: 'label',
      target: 'type_label',
    },
    {
      key: 'file.url',
      label: 'Lampiran',
      type: 'attachment',
      sortable: false,
      width: 226.5,
      is_show: true,
    },
    {
      key: 'created_at',
      label: 'Tanggal Upload',
      type: 'datetime',
      sortable: true,
      width: 226.5,
      is_show: true,
    },
  ],
};
