export const PageConfig = {
  url: '/forum/report',
  detailUrl: '/forum/report/:id',
  moduleTitle: 'Daftar Laporan',
  moduleSlug: 'report',
  pageTitle: 'Daftar Laporan',
  baseEnpoint: '/cms/forum/reports',
  primaryKey: 'id',
  maxBottomIndexDropdown: 2,
  enableSearchTools: true,
  enableTools: false,
  enableExportTools: true,
  enableExportSingleTools: true,
  enableTemplateTools: true,
  enableImportTools: false,
  enableFilterTools: true,
  enableActions: true,
  enableCreate: false,
  enableDetails: true,
  enableEdit: false,
  enableDelete: true,
  enableBulkDelete: false,
  enablePagination: true,
  enableLimitPerPage: true,
  enableRefreshTable: false,
  listFields: [
    {
      key: 'id',
      label: 'USER ID',
      sortable: false,
      width: 'auto',
      is_show: false,
    },
    {
      key: 'user',
      label: 'Pemilik Konten',
      sortable: false,
      width: 'auto',
      is_show: true,
    },
    {
      key: 'role',
      label: 'Role',
      sortable: false,
      width: 'auto',
      is_show: true,
    },
    {
      key: 'type_label',
      label: 'Perihal',
      sortable: false,
      width: 'auto',
      is_show: true,
    },
    {
      key: 'count',
      label: 'Jumlah Laporan',
      sortable: false,
      width: 'auto',
      is_show: true,
    },
    {
      key: 'is_active',
      label: 'Status',
      sortable: false,
      width: 'auto',
      is_show: true,
      status: true,
      target: 'status_label',
    },
  ],
};
