<?php

namespace App\Providers;

class RegisterPolicy
{
    const POLICIES = [
        \App\Models\Base\User::class => \App\Policies\Base\UserPolicy::class,
        \App\Models\Base\HarshWord::class => \App\Policies\Base\HarshWordPolicy::class,
        \App\Models\Base\ActivityLog::class => \App\Policies\Base\ActivityLogPolicy::class,
        \App\Models\Master\Province::class => \App\Policies\Master\ProvincePolicy::class,
        \App\Models\Master\Cities::class => \App\Policies\Master\CitiesPolicy::class,
        \App\Models\Master\ContentNotification::class => \App\Policies\Master\ContentNotificaionPolicy::class,
        \App\Models\Master\ContentNotificationLog::class => \App\Policies\Master\ContentNotificaionLogPolicy::class,
        \App\Models\Master\Seminar::class => \App\Policies\Master\SeminarPolicy::class,
        \App\Models\Master\Certification::class => \App\Policies\Master\CertificationPolicy::class,
        \App\Models\Master\CertificationStudent::class => \App\Policies\Master\CertificationStudentPolicy::class,
        \App\Models\Base\Role::class => \App\Policies\Base\RolePolicy::class,
        \App\Models\Base\Menu::class => \App\Policies\Base\MenuPolicy::class,
        \App\Models\Forum\ForumTopic::class => \App\Policies\Forum\ForumTopicPolicy::class,
        \App\Models\Forum\ForumPost::class => \App\Policies\Forum\ForumPostPolicy::class,
        \App\Models\Forum\ForumComment::class => \App\Policies\Forum\ForumCommentPolicy::class,
        \App\Models\Forum\ForumLike::class => \App\Policies\Forum\ForumLikePolicy::class,
        \App\Models\Forum\ForumReport::class => \App\Policies\Forum\ForumReportPolicy::class,
        \App\Models\Base\File::class => \App\Policies\Base\FilePolicy::class,
        \App\Models\Master\Notification::class => \App\Policies\Master\NotificaionPolicy::class,
        \App\Models\Base\Setting::class => \App\Policies\Base\SettingPolicy::class,
        \App\Models\Base\UserFiles::class => \App\Policies\Base\UserFilesPolicy::class,
        \App\Models\Training\Question::class => \App\Policies\Training\QuestionPolicy::class,
        \App\Models\Training\QuestionItem::class => \App\Policies\Training\QuestionItemPolicy::class,
        \App\Models\Training\ExamTemplate::class => \App\Policies\Training\ExamTemplatePolicy::class,
        \App\Models\Training\ExamTemplateItem::class => \App\Policies\Training\ExamTemplateItemPolicy::class,
        \App\Models\Training\Event::class => \App\Policies\Training\EventPolicy::class,
        \App\Models\Training\Article::class => \App\Policies\Training\ArticlePolicy::class,
        \App\Models\Training\Course::class => \App\Policies\Training\CoursePolicy::class,
        \App\Models\Training\CourseItem::class => \App\Policies\Training\CourseItemPolicy::class,
        \App\Models\Training\UserCourse::class => \App\Policies\Training\UserCoursePolicy::class,
        \App\Models\Training\UserCourseItem::class => \App\Policies\Training\UserCourseItemPolicy::class,
        \App\Models\Training\UserExam::class => \App\Policies\Training\UserExamPolicy::class,
        \App\Models\Training\UserExamQuestion::class => \App\Policies\Training\UserExamQuestionPolicy::class,
        \App\Models\Training\UserExamQuestionItem::class => \App\Policies\Training\UserExamQuestionItemPolicy::class,
        \App\Models\Training\Interview::class => \App\Policies\Training\InterviewPolicy::class,
        \App\Models\Training\Document::class => \App\Policies\Training\DocumentPolicy::class,
        \App\Models\Training\Program::class => \App\Policies\Training\ProgramPolicy::class,
        \App\Models\Finance\Batch::class => \App\Policies\Finance\BatchPolicy::class,
        \App\Models\Finance\BatchUser::class => \App\Policies\Finance\BatchUserPolicy::class,
        \App\Models\Finance\Transaction::class => \App\Policies\Finance\TransactionPolicy::class,
        \App\Models\Finance\TransactionItem::class => \App\Policies\Finance\TransactionItemPolicy::class,
        \App\Models\Finance\PaymentAdapter::class => \App\Policies\Finance\PaymentAdapterPolicy::class,
        \App\Models\Finance\Payment::class => \App\Policies\Finance\PaymentPolicy::class,
        \App\Models\Finance\PaymentProof::class => \App\Policies\Finance\PaymentProofPolicy::class,
        \App\Models\Finance\Installment::class => \App\Policies\Finance\InstallmentPolicy::class,
        \App\Models\Finance\BankAccount::class => \App\Policies\Finance\BankAccountPolicy::class,
        \App\Models\Finance\Bank::class => \App\Policies\Finance\BankPolicy::class,
        \App\Models\Finance\Price::class => \App\Policies\Finance\PricePolicy::class,
        \App\Models\Finance\PaymentContent::class=>\App\Policies\Finance\PaymentContentPolicy::class,
        \App\Models\Finance\PaymentContentItem::class=>\App\Policies\Finance\PaymentContentItemPolicy::class,
    ];
}
