export const PageConfig = {
  url: '/training/module',
  detailUrl: '/training/module/detail/:id',
  detailModulelUrl: '/training/module/detail/',
  createUrl: '/training/module/create',
  moduleTitle: 'Modul Pelatihan',
  pageTitle: 'Tabel Modul Pelatihan',
  baseEnpoint: '/training/course-items/module',
  primaryKey: 'id',
  maxBottomIndexDropdown: 2,
  enableSearchTools: true,
  enableTools: true,
  enableExportTools: true,
  enableTemplateTools: false,
  enableImportTools: false,
  enableFilterTools: true,
  enableActions: true,
  enableCreate: true,
  enableDetail: false,
  enableEdit: true,
  enableDelete: true,
  enableBulkDelete: false,
  enablePagination: true,
  enableLimitPerPage: true,
  enableRefreshTable: false,
  listFields: [
    {
      key: 'title',
      label: 'Modul Pelatihan',
      sortable: false,
      width: 234,
      is_show: true,
    },
    {
      key: 'course.title',
      label: 'Kategori Modul',
      sortable: false,
      width: 168,
      is_show: true,
    },
    {
      key: 'program_type',
      label: 'Program Pelatihan',
      sortable: true,
      width: 168,
      is_show: true,
      type: 'label',
      target: 'program_type_label',
    },
    {
      key: 'level_module_label',
      label: 'Level Modul',
      sortable: false,
      width: 168,
      is_show: true,
    },
    {
      key: 'access_module',
      label: 'Akses Modul',
      sortable: true,
      width: 168,
      is_show: true,
      type: 'label',
      target: 'access_module_label',
    },
  ],
};
