export const PageConfig = {
  url: '/management/role',
  createUrl: '/management/role/create',
  editUrl: '/management/role/edit/:id',
  detailUrl: '/management/role/detail/:id',
  moduleTitle: 'Daftar Role',
  pageTitle: 'Daftar Role',
  createTitle: 'Buat Role',
  editTitle: 'Edit Role',
  baseEnpoint: '/base/roles',
  primaryKey: 'id',
  maxBottomIndexDropdown: 2,
  enableSearchTools: true,
  enableTools: true,
  enableExportTools: false,
  enableTemplateTools: false,
  enableImportTools: false,
  enableFilterTools: false,
  enableActions: true,
  enableCreate: true,
  enableDetail: false,
  enableEdit: true,
  enableDelete: true,
  enableBulkDelete: false,
  enablePagination: true,
  enableLimitPerPage: true,
  enableRefreshTable: false,
  listFields: [
    {
      key: 'name',
      label: 'Nama Role',
      sortable: true,
      width: 250.5,
      is_show: true,
    },
    {
      key: 'users_count',
      target: 'user',
      label: 'Jumlah Pengguna',
      sortable: true,
      is_num: true,
      width: 250.5,
      is_show: true,
    },
    {
      key: 'status',
      label: 'Status',
      sortable: false,
      width: 250.5,
      is_show: true,
      status: true,
      target: 'status_label',
    },
  ],
  listMenus: [
    {
      key: 'name',
      label: 'Fitur',
      sortable: false,
      width: 479,
      is_show: true,
    },
    {
      key: 'description',
      label: 'Deskripsi',
      sortable: false,
      width: 479,
      is_show: true,
    },
  ],
};
